//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] config_simple {
            get {
                object obj = ResourceManager.GetObject("config_simple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 #简体中文
        ///
        ///V2RayW already Running=V2RayW已经运行
        ///You can find it in your tray.=您可以在托盘中找到它.
        ///Wrong or missing v2ray core file!=V2Ray核心文件丢失或错误
        ///Download it right now?=要下载正确的核心吗?
        ///
        ///#ConfigForm
        ///Main inbound:=主inbound:
        ///Share Over LAN=通过LAN分享
        ///Socks5 Port:=Socks5端口:
        ///Support UDP=支持UDP
        ///Http Port:=Http端口:
        ///If the protocol or port is changed, the pac file also needs manual modification.=如果协议或端口被修改，PAC文件也需要手动修改。
        ///seperated by comma(,)=使用英文逗号分隔(,)
        ///V2Ray Servers=V2Ray服务器
        ///Address:=服务器地址:
        ///Security:=加密协议:
        ///transport settings...=传输设置...
        ///N [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Lang_zh_cn {
            get {
                return ResourceManager.GetString("Lang_zh_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///      &quot;sendThrough&quot;: &quot;0.0.0.0&quot;,
        ///      &quot;mux&quot;: {
        ///        &quot;enabled&quot;: false,
        ///        &quot;concurrency&quot;: 8
        ///      },
        ///      &quot;protocol&quot;: &quot;vmess&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot;vnext&quot;: [
        ///          {
        ///            &quot;address&quot;: &quot;server.cc&quot;,
        ///            &quot;users&quot;: [
        ///              {
        ///                &quot;id&quot;: &quot;12345678-1234-1234-1234-12345678abcd&quot;,
        ///                &quot;alterId&quot;: 0,
        ///                &quot;security&quot;: &quot;auto&quot;,
        ///                &quot;level&quot;: 0
        ///              }
        ///            ],
        ///            &quot;port&quot;: 12345
        ///          }
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VmessTemplate {
            get {
                return ResourceManager.GetString("VmessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon vw256 {
            get {
                object obj = ResourceManager.GetObject("vw256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
